### PR TITLE
Comet integration improvements

### PR DESCRIPTION
**Pull request by DN6**
This PR:

1. Fixes PR Curve logging issue with Comet  and the `add_pr_curve` method. Comet will now log the computed PR curve as opposed to the Predictions and Labels
2. Fixes the logging issue for raw Histogram Data to Comet from the `add_histogram_raw` method. Comet will now log the histogram data, instead of the generated Proto file.

### CODE REVIEW

**Comment by XuJing1022** [comment]
您的邮件，我已收到，谢谢，祝好~

**Comment by DN6** [comment]
Hi @lanpa. Would really appreciate your review on these improvements to the Comet logger. Thank you!

**Comment by DN6** [comment]
@lanpa  I've applied the recommended changes.

**Comment by DN6** [comment]
@lanpa  Just following up. Is there anything else needed from my side to approve the merge?

**Comment by lanpa** [comment]
Thanks!

**Comment by DN6** [comment]
Hello @lanpa. Thank you for merging! Would you be able to share when you're planning on making the next release?

**Comment by lanpa** [comment]
Sure. It has been six months since last release, so it's time to make a release this weekend. Thank you for the contribution.

**Comment by lanpa** [comment]
@DN6 uploaded :)

**Pull request merged**
