### PR TITLE
Fix issue #210.

### PR DESCRIPTION
**Pull request by hzxie**

### CODE REVIEW

**Comment by hzxie** [comment]
I think the failure of CI is something wrong with your config with Travis CI, instead of my code.

**Comment by lanpa** [comment]
That's a styling issue:
flake8 tensorboardX
tensorboardX/x2num.py:116:43: W291 trailing whitespace

**Comment by ClementPinard** [comment]
So the tensorflow convention can be a good start (`NCHW` or `NHWC`, `NCDHW` or `NDHWC`) but it may lack the readability if someone is not aware of the naming convention. Other than that maybe a boolean parameter ? `channel_first=True/False`

**Comment by hzxie** [comment]
@ClementPinard
Sorry, I can't understand.
Do you prefer `NCHW`, `NHWC`, `NCDHW`, `NDHWC` or a boolean parameter?

**Comment by ClementPinard** [comment]
I don't have strong about either these two, I was just suggesting two different solution that I'd be fine with. If ultimately had to choose, I'd say probably the `NHCW` thing to keep consistency with other conventions regarding this issue, but I'd be happy with either these two propositions

**Comment by hzxie** [comment]
@ClementPinard 
OK.
Now the problem is how to determine the data format according to the given image?

**Comment by ClementPinard** [comment]
Ah sorry, didn't see your comment above about letting the user define their data format, that was actually my intention, since I don't see a trivial way to determine it directly from data :)

**Comment by lanpa** [comment]
@ClementPinard  naming conventions regarding NCHW, NHWC is not a big issue, we can document it in the docstring. `NCDHW` may be useful for  `add_video` function in the future. I think this is better than true/false.

**Comment by hzxie** [comment]
@ClementPinard @lanpa 
But it will cause API change.
Are you sure to do this?

**Comment by lanpa** [comment]
Since NCHW, NHWC, NCDHW, NDHWC has no co-occured alphabet. If user passes this argument, we can simply match the character and do the transpose. In this way, any permutation can be dealt with. The change should be backward compatible, right?
`add_image('tag', tensor, n_iter, format='NCHW')`

**Comment by ClementPinard** [comment]
It will be an API change, but not necessarily a breaking one, since we can add a default parameter to it.

To avoid breaking all codes from before, we should probably have a default data format dependant to tensor nature (e.g. numpy is `NHWC`, pytorch is `NCHW`), so maybe add in all `prepare_something` functions along with `modality` a `data_format` argument whose default won't be the same, with `add_image` default data format set to `None`.

**Comment by lanpa** [comment]
A general fix is here: 1e8f6ad. closing this.

**Pull request closed without merging**
