### PR TITLE
Upgrade to protobuf 4

### PR DESCRIPTION
**Pull request by fg91**
In this PR I upgrade from protobuf `3.x` to `4.x`.

This upgrade is important because many libraries in the ML tooling landscape have already done the upgrade and in newest versions don't support protobuf version `3.x` anymore. This means that `tensborboardX` cannot be used with newer versions of some tools.

---

To make the tests pass after the upgrade to protobuf 4, I had to change the way protobufs are compared to expected values in the tests. Currently, the expected value is loaded from a file that looks e.g. like this ...

```
value {
  tag: "dummy/text_summary"
  tensor {
    dtype: DT_STRING
    tensor_shape {
      dim {
        size: 1
      }
    }
    string_val: "text 123"
  }
  metadata {
    plugin_data {
      plugin_name: "text"
    }
  }
}
```

... into a string. The comparison then happens based on the string representation of the protobuf `Message`.

However, after the upgrade, the string representation is in a different order:

```
value {
  tag: "dummy/text_summary"
  metadata {
    plugin_data {
      plugin_name: "text"
    }
  }
  tensor {
    dtype: DT_STRING
    tensor_shape {
      dim {
        size: 1
      }
    }
    string_val: "text 123"
  }
}
```

This makes the `assert`s fail.

Since this is an un-ordered data structure anways, it is better to not compare the string representation but the actual protobuf `Messages`. I modify the comparison logic to load the expected values back into protobuf `Messages` to make the tests pass again.

### CODE REVIEW

**Comment by lanpa** [comment]
Thanks! I will review it asap.

**Comment by fg91** [comment]
> Thanks! I will review it asap.

Thanks!

**Comment by dvaldivia** [comment]
This will probably address the exception shown when importing `tensorboardX` with the latest PyTorch perhaps?

```
Unexpected exception formatting exception. Falling back to standard exception
Traceback (most recent call last):
  File "/Users/dvaldivia/mindev/writing-ml-pipelines/venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/nz/wlp9tb8s3d774wlqjvgh65qh0000gn/T/ipykernel_61582/1461859601.py", line 2, in <module>
    from tensorboardX import SummaryWriter
  File "/Users/dvaldivia/mindev/writing-ml-pipelines/venv/lib/python3.9/site-packages/tensorboardX/__init__.py", line 5, in <module>
    from .torchvis import TorchVis
  File "/Users/dvaldivia/mindev/writing-ml-pipelines/venv/lib/python3.9/site-packages/tensorboardX/torchvis.py", line 10, in <module>
    from .writer import SummaryWriter
  File "/Users/dvaldivia/mindev/writing-ml-pipelines/venv/lib/python3.9/site-packages/tensorboardX/writer.py", line 16, in <module>
    from .comet_utils import CometLogger
  File "/Users/dvaldivia/mindev/writing-ml-pipelines/venv/lib/python3.9/site-packages/tensorboardX/comet_utils.py", line 7, in <module>
    from .summary import _clean_tag
  File "/Users/dvaldivia/mindev/writing-ml-pipelines/venv/lib/python3.9/site-packages/tensorboardX/summary.py", line 12, in <module>
    from .proto.summary_pb2 import Summary
  File "/Users/dvaldivia/mindev/writing-ml-pipelines/venv/lib/python3.9/site-packages/tensorboardX/proto/summary_pb2.py", line 16, in <module>
    from tensorboardX.proto import tensor_pb2 as tensorboardX_dot_proto_dot_tensor__pb2
  File "/Users/dvaldivia/mindev/writing-ml-pipelines/venv/lib/python3.9/site-packages/tensorboardX/proto/tensor_pb2.py", line 16, in <module>
    from tensorboardX.proto import resource_handle_pb2 as tensorboardX_dot_proto_dot_resource__handle__pb2
  File "/Users/dvaldivia/mindev/writing-ml-pipelines/venv/lib/python3.9/site-packages/tensorboardX/proto/resource_handle_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/Users/dvaldivia/mindev/writing-ml-pipelines/venv/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 561, in __new__
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dvaldivia/mindev/writing-ml-pipelines/venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2105, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "/Users/dvaldivia/mindev/writing-ml-pipelines/venv/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1396, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/Users/dvaldivia/mindev/writing-ml-pipelines/venv/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1287, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/Users/dvaldivia/mindev/writing-ml-pipelines/venv/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1140, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/Users/dvaldivia/mindev/writing-ml-pipelines/venv/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1055, in format_exception_as_a_whole
    frames.append(self.format_record(record))
  File "/Users/dvaldivia/mindev/writing-ml-pipelines/venv/lib/python3.9/site-packages/IPython/core/ultratb.py", line 955, in format_record
    frame_info.lines, Colors, self.has_colors, lvals
  File "/Users/dvaldivia/mindev/writing-ml-pipelines/venv/lib/python3.9/site-packages/IPython/core/ultratb.py", line 778, in lines
    return self._sd.lines
  File "/Users/dvaldivia/mindev/writing-ml-pipelines/venv/lib/python3.9/site-packages/stack_data/utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/dvaldivia/mindev/writing-ml-pipelines/venv/lib/python3.9/site-packages/stack_data/core.py", line 734, in lines
    pieces = self.included_pieces
  File "/Users/dvaldivia/mindev/writing-ml-pipelines/venv/lib/python3.9/site-packages/stack_data/utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/dvaldivia/mindev/writing-ml-pipelines/venv/lib/python3.9/site-packages/stack_data/core.py", line 681, in included_pieces
    pos = scope_pieces.index(self.executing_piece)
  File "/Users/dvaldivia/mindev/writing-ml-pipelines/venv/lib/python3.9/site-packages/stack_data/utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/dvaldivia/mindev/writing-ml-pipelines/venv/lib/python3.9/site-packages/stack_data/core.py", line 660, in executing_piece
    return only(
  File "/Users/dvaldivia/mindev/writing-ml-pipelines/venv/lib/python3.9/site-packages/executing/executing.py", line 190, in only
    raise NotOneValueFound('Expected one value, found 0')
executing.executing.NotOneValueFound: Expected one value, found 0
```

**Comment by lanpa** [comment]
@david-lindner Is `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python [your code dot py]` a workaround for you?

**Comment by fg91** [comment]
Thanks for pushing this over the finish line @lanpa! 🙏

**Pull request merged**
