### PR TITLE
Remove upper pins on protobuf

### PR DESCRIPTION
**Pull request by lanpa**
See #692

### CODE REVIEW

**Comment by daliu** [comment]
Thanks for working on this! Does https://github.com/lanpa/tensorboardX/blob/master/test-requirements.txt#L5 also need to be refactored?

**Comment by LarsDu** [comment]
This hasn't merged yet?

**Review by LarsDu — APPROVED** [review]
I approve this change.
We need this badly now, as it just so happens the `ray` package uses tensorboardx for logging integrations.

**Comment by lanpa** [comment]
@LarsDu Thanks for the approval. I totally forgot this small PR!

**Comment by dliu-fn** [comment]
Thanks so much Ian, we really appreciate it! Do you think you might do a release soon?

**Pull request merged**
