### PR TITLE
[WIP] Only run writer close test once

### PR DESCRIPTION
**Pull request by orionr**
This had some issues in our internal PyTorch testing infrastructure.

### CODE REVIEW

**Comment by lanpa** [comment]
The loop was added intentionally. What is the issue?

**Comment by orionr** [comment]
I'm not 100% sure this solves the issue (still testing internally) but we have some internal stress tests that fail on this test with the loop. I still need to verify this fixes the issue, but can you explain the reason for having the loop? Was this essentially a stress test?

**Comment by lanpa** [comment]
https://github.com/lanpa/tensorboardX/issues/108

I remember that I tried to fix this long time ago and suspected that it might be related to python's GIL.
The maximum `open/close` allowed are different on different OS.

**Comment by orionr** [comment]
That's possible. Just landed internal changes to see if this fixes the issue we were seeing or not. I'll report back.

**Comment by orionr** [comment]
Looks like this did fix the internal case. It's possible that we could have a few loops, but the large number was definitely an issue.

**Comment by lanpa** [comment]
Yeah, I believe it needs a major rewrite with the multiprocessing module.

**Pull request merged**
