### PR TITLE
Fix git based package versioning for setuptools >= 67.0.0

### PR DESCRIPTION
**Pull request by fellhorn**
# Explanation
setuptools no longer accepts invalid version strings. The custom implementation used in `setup.py` produces invalid strings like `v2.5.1-16-g2169c4a-2169c4a` for the current commit on master:

```py
File "/home/fellhorn/.pyenv/versions/tensorboardX/python3.9/site-packages/setuptools/_vendor/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'v2.5.1-16-g2169c4a-2169c4a'
```

Previous versions of setuptools handled invalid versions with a warning.

# Changes
This PR replaces the custom git versioning implementation with `setuptools_scm`.

### CODE REVIEW

**Comment by fellhorn** [comment]
@lanpa [5a1cd78](https://github.com/lanpa/tensorboardX/pull/691/commits/5a1cd7884c791c295aaacca5d7dc55c8a1febc5e) should fix the `ImportError` when the package is not installed (e.g. here in CI).

**Comment by lanpa** [comment]
Error caused by: https://about.codecov.io/blog/message-regarding-the-pypi-package/

**Comment by lanpa** [comment]
@fellhorn Hi, thanks for the fix. The latest failure was cause by codecov. But I can't push the CI update to your repo, would you pull the master branch and trigger the test again?

**Comment by fellhorn** [comment]
> @fellhorn Hi, thanks for the fix. The latest failure was cause by codecov. But I can't push the CI update to your repo, would you pull the master branch and trigger the test again?

Hi @lanpa, just synced with master. Any idea where the codecov difference comes from or if it matters?

**Comment by lanpa** [comment]
Thanks for the fix! @fellhorn

**Pull request merged**
